name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
    - name: Archive Stripes zip
      uses: actions/upload-artifact@v1
      with:
        name: stripes-2.0.0-SNAPSHOT.zip
        path: dist/target/stripes-2.0.0-SNAPSHOT.zip
    - name: Archive Stripes bundle zip
      uses: actions/upload-artifact@v1
      with:
        name: stripes-2.0.0-SNAPSHOT-bundle.jar
        path: dist/target/stripes-2.0.0-SNAPSHOT-bundle.jar
    - name: Zip tlddoc documentation
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r /home/runner/work/stripes/stripes/docs/tlddoc.zip /home/runner/work/stripes/stripes/stripes/target/site/tlddoc
    - name: Archive tlddoc documentation
      uses: actions/upload-artifact@v1
      with:
        name: tlddoc.zip
        path: docs
    - name: Zip apidocs documentation
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r /home/runner/work/stripes/stripes/docs/apidocs.zip /home/runner/work/stripes/stripes/stripes/target/apidocs
    - name: Archive apidocs documentation
      uses: actions/upload-artifact@v1
      with:
        name: apidocs.zip
        path: docs