name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: stripes-1.7.0-SNAPSHOT.zip
        path: dist/target/stripes-1.7.0-SNAPSHOT.zip
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: stripes-1.7.0-SNAPSHOT-bundle.jar
        path: dist/target/stripes-1.7.0-SNAPSHOT-bundle.jar