name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/dist/target/*.zip,/dist/target/*.jar"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}